[package]
name = "cap-ffmpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-sidecar = "1.1.0"
cap-utils = { path = "../utils" }
tauri = { workspace = true }
tauri-plugin-shell = "2.0.0-rc"
nix = { version = "0.29.0", features = ["signal"] }
