export const CLIENT_EVENT_V1_BASELINE = {
	page_view: {
		platforms: ["web"],
		properties: [
			"first_touch_source:string:attribution::optional:nonnullable",
			"first_touch_medium:string:attribution::optional:nonnullable",
			"first_touch_campaign:string:attribution::optional:nonnullable",
			"first_touch_content:string:attribution::optional:nonnullable",
			"first_touch_term:string:attribution::optional:nonnullable",
			"first_touch_gclid:string:identifier::optional:nonnullable",
			"first_touch_fbclid:string:identifier::optional:nonnullable",
			"session_touch_source:string:attribution::optional:nonnullable",
			"session_touch_medium:string:attribution::optional:nonnullable",
			"session_touch_campaign:string:attribution::optional:nonnullable",
			"session_touch_content:string:attribution::optional:nonnullable",
			"session_touch_term:string:attribution::optional:nonnullable",
			"session_touch_gclid:string:identifier::optional:nonnullable",
			"session_touch_fbclid:string:identifier::optional:nonnullable",
			"last_touch_source:string:attribution::optional:nonnullable",
			"last_touch_medium:string:attribution::optional:nonnullable",
			"last_touch_campaign:string:attribution::optional:nonnullable",
			"last_touch_content:string:attribution::optional:nonnullable",
			"last_touch_term:string:attribution::optional:nonnullable",
			"last_touch_gclid:string:identifier::optional:nonnullable",
			"last_touch_fbclid:string:identifier::optional:nonnullable",
			"hostname:string:hostname::required:nonnullable",
			"is_session_entry:boolean:::required:nonnullable",
			"session_started_at:string:timestamp::required:nonnullable",
		],
	},
	page_engagement: {
		platforms: ["web"],
		properties: [
			"page_view_id:string:identifier::required:nonnullable",
			"session_started_at:string:timestamp::required:nonnullable",
			"engaged_ms:number:::required:nonnullable",
			"max_scroll_depth:number:::required:nonnullable",
		],
	},
	download_cta_clicked: {
		platforms: ["web"],
		properties: [
			"source_page:string:category::required:nonnullable",
			"cta_location:string:category::required:nonnullable",
			"target:string:category::optional:nonnullable",
			"detected_platform:string:category::optional:nonnullable",
			"is_intel:boolean:::optional:nonnullable",
		],
	},
	pricing_cta_clicked: {
		platforms: ["web"],
		properties: [
			"source_page:string:category::required:nonnullable",
			"cta_location:string:category::optional:nonnullable",
			"plan_name:string:category::optional:nonnullable",
			"authenticated:boolean:::optional:nonnullable",
			"is_pro:boolean:::optional:nonnullable",
			"cta_action:string:category::optional:nonnullable",
			"target_billing_period:string:category::optional:nullable",
		],
	},
	cli_install_command_copied: {
		platforms: ["web"],
		properties: [
			"source_page:string:category::required:nonnullable",
			"detected_platform:string:category::required:nonnullable",
		],
	},
	auth_started: {
		platforms: ["web"],
		properties: [
			"method:string::apple|email|google:required:nonnullable",
			"is_signup:boolean:::required:nonnullable",
			"auth_surface:string::login|signup|share_overlay:required:nonnullable",
		],
	},
	auth_email_sent: {
		platforms: ["web"],
		properties: [
			"method:string::email:required:nonnullable",
			"is_signup:boolean:::required:nonnullable",
			"auth_surface:string::login|signup|share_overlay:required:nonnullable",
		],
	},
	user_signed_in: { platforms: ["web", "desktop", "mobile"], properties: [] },
	user_signed_out: { platforms: ["desktop", "mobile"], properties: [] },
	recording_started: {
		platforms: ["desktop", "mobile"],
		properties: [
			"mode:string:category::required:nonnullable",
			"target_kind:string:category::required:nonnullable",
			"has_camera:boolean:::required:nonnullable",
			"has_mic:boolean:::required:nonnullable",
			"has_system_audio:boolean:::required:nonnullable",
			"target_fps:number:::required:nonnullable",
			"target_width:number:::required:nonnullable",
			"target_height:number:::required:nonnullable",
			"fragmented:boolean:::required:nonnullable",
			"custom_cursor_capture:boolean:::required:nonnullable",
		],
	},
	recording_start_failed: {
		platforms: ["desktop", "mobile"],
		properties: [
			"mode:string:category::required:nonnullable",
			"failure_class:string:category::required:nonnullable",
		],
	},
	recording_completed: {
		platforms: ["desktop", "mobile"],
		properties: [
			"mode:string:category::required:nonnullable",
			"status:string:category::required:nonnullable",
			"duration_secs:number:::required:nonnullable",
			"segment_count:number:::required:nonnullable",
			"track_failure_count:number:::required:nonnullable",
			"error_class:string:category::optional:nonnullable",
			"video_frames_captured:number:::optional:nonnullable",
			"video_frames_dropped:number:::optional:nonnullable",
			"drop_rate_pct:number:::optional:nonnullable",
			"capture_stalls_count:number:::optional:nonnullable",
			"capture_stalls_max_ms:number:::optional:nonnullable",
			"mixer_stalls_count:number:::optional:nonnullable",
			"mixer_stalls_max_ms:number:::optional:nonnullable",
			"audio_gaps_count:number:::optional:nonnullable",
			"audio_gaps_total_ms:number:::optional:nonnullable",
			"queue_saturation_count:number:::optional:nonnullable",
			"queue_max_depth:number:::optional:nonnullable",
			"queue_capacity:number:::optional:nonnullable",
			"frame_drop_count:number:::optional:nonnullable",
			"frame_drop_rate_high_count:number:::optional:nonnullable",
			"source_restarts_count:number:::optional:nonnullable",
			"muxer_crash_count:number:::optional:nonnullable",
			"audio_degraded_count:number:::optional:nonnullable",
			"dropped_mic_messages:number:::optional:nonnullable",
		],
	},
	multipart_upload_complete: {
		platforms: ["desktop", "mobile"],
		properties: [
			"duration:number:::required:nonnullable",
			"length:number:::required:nonnullable",
			"size:number:::required:nonnullable",
		],
	},
	multipart_upload_failed: {
		platforms: ["desktop", "mobile"],
		properties: [
			"duration:number:::required:nonnullable",
			"failure_class:string:category::required:nonnullable",
		],
	},
	recording_recovery_failed: {
		platforms: ["desktop"],
		properties: [
			"trigger:string:category::required:nonnullable",
			"failure_class:string:category::required:nonnullable",
		],
	},
	analytics_delivery_loss: {
		platforms: ["desktop"],
		properties: [
			"failure_class:string:category::required:nonnullable",
			"failed_event_name:string:category::required:nonnullable",
			"status:number:::optional:nullable",
			"count:number:::required:nonnullable",
			"first_sequence:number:::required:nonnullable",
			"last_sequence:number:::required:nonnullable",
			"first_failed_at_ms:number:::required:nonnullable",
			"last_failed_at_ms:number:::required:nonnullable",
		],
	},
	onboarding_milestone_completed: {
		platforms: ["web"],
		properties: [
			"milestone:string::welcome|organization_setup|custom_domain|invite_team|download|skip_all:required:nonnullable",
			"skipped:boolean:::required:nonnullable",
		],
	},
	export_button_clicked: { platforms: ["desktop"], properties: [] },
	export_fps_changed: {
		platforms: ["desktop"],
		properties: ["fps:number:::required:nonnullable"],
	},
	export_started: {
		platforms: ["desktop"],
		properties: [
			"destination:string::clipboard|file|share_link:required:nonnullable",
			"format:string:category::required:nonnullable",
			"resolution:string:category::required:nonnullable",
			"fps:number:::required:nonnullable",
		],
	},
	export_completed: {
		platforms: ["desktop"],
		properties: [
			"destination:string::clipboard|file|share_link:required:nonnullable",
			"format:string:category::required:nonnullable",
			"resolution:string:category::required:nonnullable",
			"fps:number:::required:nonnullable",
		],
	},
	export_failed: {
		platforms: ["desktop"],
		properties: [
			"destination:string::clipboard|file|share_link:required:nonnullable",
			"format:string:category::required:nonnullable",
			"resolution:string:category::required:nonnullable",
			"fps:number:::required:nonnullable",
			"failure_class:string::cancelled|authentication|plan|network|render|unknown:required:nonnullable",
		],
	},
	create_shareable_link_clicked: {
		platforms: ["desktop"],
		properties: [
			"resolution:string:category::required:nonnullable",
			"fps:number:::required:nonnullable",
			"has_existing_auth:boolean:::required:nonnullable",
		],
	},
	camera_selected: {
		platforms: ["desktop"],
		properties: ["enabled:boolean:::required:nonnullable"],
	},
	microphone_selected: {
		platforms: ["desktop"],
		properties: ["enabled:boolean:::required:nonnullable"],
	},
	screenshot_view_clicked: { platforms: ["desktop"], properties: [] },
	screenshot_editor_clicked: { platforms: ["desktop"], properties: [] },
	screenshot_folder_clicked: { platforms: ["desktop"], properties: [] },
	screenshot_copy_clicked: { platforms: ["desktop"], properties: [] },
	screenshot_share_clicked: { platforms: ["desktop"], properties: [] },
	recording_view_clicked: { platforms: ["desktop"], properties: [] },
	recording_folder_clicked: { platforms: ["desktop"], properties: [] },
	recording_copy_clicked: { platforms: ["desktop"], properties: [] },
	recording_editor_clicked: { platforms: ["desktop"], properties: [] },
	tool_interaction: {
		platforms: ["web"],
		properties: [
			"tool:string::trimmer|speed_controller|media_converter:required:nonnullable",
			"action:string::loaded|invalid_file_type|file_too_large|file_selected|process_started|process_completed|process_failed|download|reset:required:nonnullable",
			"source_format:string:category::optional:nonnullable",
			"target_format:string:category::optional:nonnullable",
			"operation:string:category::optional:nonnullable",
			"mime_category:string:category::optional:nonnullable",
			"input_size_bucket:string:category::optional:nonnullable",
			"output_size_bucket:string:category::optional:nonnullable",
			"duration_ms:number:::optional:nonnullable",
			"speed_factor:number:::optional:nonnullable",
			"failure_class:string:category::optional:nonnullable",
		],
	},
	experiment_exposed: {
		platforms: ["web"],
		properties: [
			"experiment_id:string:identifier::required:nonnullable",
			"variant:string:identifier::required:nonnullable",
			"assignment_version:string:identifier::required:nonnullable",
		],
	},
} as const;
