[package]
name = "cap-flags"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
specta.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
