[package]
name = "cap-flags"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.214"
# TODO(Ilya): Remove with next tauri and specta updates
specta.workspace = true

specta-util.workspace = true
