[package]
name = "scap"
version = "0.1.0"
edition = "2024"

[dependencies]
cap-displays = { path = "../displays" }

[target.'cfg(windows)'.dependencies]
scap-direct3d = { path = "../scap-direct3d" }

[target.'cfg(target_os = "macos")'.dependencies]
scap-screencapturekit = { path = "../scap-screencapturekit" }

[lints]
workspace = true
