/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
	export interface Resource {
		AuroraDB: {
			clusterArn: string;
			database: string;
			host: string;
			password: string;
			port: number;
			reader: string;
			secretArn: string;
			type: "sst.aws.Aurora";
			username: string;
		};
		DATABASE_URL_MYSQL: {
			type: "sst.sst.Secret";
			value: string;
		};
		GITHUB_PAT: {
			type: "sst.sst.Secret";
			value: string;
		};
		MyApi: {
			type: "sst.aws.ApiGatewayV2";
			url: string;
		};
		Runner: {
			service: string;
			type: "sst.aws.Service";
		};
		ShardManager: {
			service: string;
			type: "sst.aws.Service";
		};
		Vpc: {
			type: "sst.aws.Vpc";
		};
	}
}
/// <reference path="sst-env.d.ts" />

import "sst";
