/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
	export interface Resource {
		DISCORD_BOT_TOKEN: {
			type: "sst.sst.Secret";
			value: string;
		};
		DiscordBotScript: {
			type: "sst.cloudflare.Worker";
		};
		GITHUB_APP_PRIVATE_KEY: {
			type: "sst.sst.Secret";
			value: string;
		};
	}
}
/// <reference path="sst-env.d.ts" />

import "sst";
