name: Setup JS (pnpm & node)
description: Sets up pnpm & node with dependencies and caching
runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install frontend dependencies
      shell: bash
      run: pnpm install
