[package]
name = "scap-ffmpeg"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
ffmpeg = { workspace = true }
cpal = { workspace = true }
scap-cpal = { optional = true, path = "../scap-cpal" }

[target.'cfg(windows)'.dependencies]
scap-direct3d = { path = "../scap-direct3d" }
windows = { workspace = true, features = [] }

[target.'cfg(target_os = "macos")'.dependencies]
scap-screencapturekit = { path = "../scap-screencapturekit" }
cidre = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
tokio = { workspace = true }
scap-targets = { path = "../scap-targets" }

[lints]
workspace = true
