[package]
name = "scap-ffmpeg"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg = { workspace = true }

[target.'cfg(windows)'.dependencies]
scap-direct3d = { path = "../scap-direct3d" }
windows = { workspace = true, features = [] }

[target.'cfg(target_os = "macos")'.dependencies]
scap-screencapturekit = { path = "../scap-screencapturekit" }
cidre = { workspace = true }

[dev-dependencies]
futures = { workspace = true }

[lints]
workspace = true
