import { PRICING } from "@/data/pricing";

export const LOOM_PURPLE = "#625DF5";

export const MIGRATE_PROMO_CODE = "MIGRATE20";

export const migrateFromLoomSeo = {
	path: "/migrate-from-loom",
	url: "https://cap.so/migrate-from-loom",
	title: "Import Loom Videos to Cap | Migrate from Loom in Minutes",
	description:
		"Paste a Loom link or upload a CSV and Cap imports your Loom videos with titles, transcripts and chapters. Open source, half the price of Loom, and 20% off Cap Pro with code MIGRATE20.",
	keywords: [
		"import loom videos",
		"loom import",
		"migrate from loom",
		"loom to cap",
		"switch from loom",
		"loom migration",
		"transfer loom videos",
		"export loom videos",
		"loom video importer",
		"loom alternative",
	],
} as const;

export const importSteps = [
	{
		name: "Paste a Loom link",
		text: "Drop any Loom share link into the importer, or upload a CSV of up to 500 links mapped to teammates and spaces.",
	},
	{
		name: "Cap fetches and re-hosts the video",
		text: "Cap pulls the recording straight from Loom in the background, keeps its title, and generates a transcript, summary and chapters. There is nothing to download or re-upload.",
	},
	{
		name: "Share it from Cap",
		text: "Every video gets a new Cap link with comments, transcript search and view counts. Your Loom links keep working until you cancel Loom, so nothing breaks while you switch.",
	},
] as const;

export const proofPoints = [
	{
		title: "Tens of thousands of recordings imported",
		body: "From single videos to organization-wide libraries with hundreds of users.",
	},
	{
		title: "Nothing to download or re-upload",
		body: "Cap fetches each recording straight from its Loom link.",
	},
	{
		title: "Storage you own",
		body: "Cap Cloud, your own S3 bucket, or Google Drive. Export MP4s any time.",
	},
] as const;

export const includedOnImport = [
	{
		title: "The video",
		body: "Every recording at the quality Loom serves it.",
	},
	{
		title: "The original title",
		body: "Cap reads the name of each Loom and keeps it.",
	},
	{
		title: "Transcript, summary and chapters",
		body: "Generated by Cap when the import finishes, so every video is searchable.",
	},
	{
		title: "Owners and spaces",
		body: "Bulk imports assign each video to a teammate and a space from your CSV.",
	},
] as const;

export const notIncludedOnImport = [
	{
		title: "Loom comments and reactions",
		body: "Those stay on Loom. Cap starts a fresh comment thread on every video.",
	},
	{
		title: "Loom view counts",
		body: "Cap counts views from the moment a video is imported.",
	},
	{
		title: "Private or deleted Looms",
		body: "A video has to be reachable from its share link. Rows that fail are listed so you can fix them and retry.",
	},
] as const;

export type ComparisonStatus = "positive" | "negative" | "warning" | "neutral";

export type ComparisonRow = {
	feature: string;
	cap: { text: string; status: ComparisonStatus };
	loom: { text: string; status: ComparisonStatus };
};

export const comparisonRows: ComparisonRow[] = [
	{
		feature: "Pricing",
		cap: {
			text: `From $${PRICING.pro.annualPerMonth} per user per month`,
			status: "positive",
		},
		loom: { text: "$18 per user per month", status: "warning" },
	},
	{
		feature: "Open source",
		cap: { text: "Yes, every line is on GitHub", status: "positive" },
		loom: { text: "No", status: "negative" },
	},
	{
		feature: "Free plan",
		cap: { text: "Unlimited Studio Mode recording", status: "positive" },
		loom: { text: "Limited features and length", status: "warning" },
	},
	{
		feature: "4K recording",
		cap: { text: "Free and paid plans", status: "positive" },
		loom: { text: "Paid plans only", status: "warning" },
	},
	{
		feature: "Bring your own storage",
		cap: { text: "Your own S3 bucket or Google Drive", status: "positive" },
		loom: { text: "Not available", status: "negative" },
	},
	{
		feature: "Team members",
		cap: { text: "Invite viewers for free", status: "positive" },
		loom: { text: "Paid per seat", status: "warning" },
	},
	{
		feature: "Custom domain",
		cap: { text: "Yes", status: "positive" },
		loom: { text: "Enterprise plan only", status: "neutral" },
	},
	{
		feature: "Import from the other tool",
		cap: { text: "Built-in Loom importer", status: "positive" },
		loom: { text: "Not available", status: "negative" },
	},
];

export const migrateFaqs = [
	{
		question: "Can I import my existing Loom videos into Cap?",
		answer:
			"Yes. Paste a Loom share link into Cap's built-in importer to bring a single video across, or upload a CSV to import your whole library. Cap fetches each recording from Loom, re-hosts it, and it appears in your library ready to share.",
	},
	{
		question: "Do I need to download my Loom videos first?",
		answer:
			"No. Cap fetches each recording directly from its Loom share link and re-hosts it for you. There is no manual downloading or re-uploading. If you would rather keep local copies as well, the free Loom video downloader saves any public Loom as an MP4.",
	},
	{
		question: "Do I need Cap Pro to import from Loom?",
		answer: `Creating a Cap account is free and takes a minute. The Loom importer is part of Cap Pro, which starts at $${PRICING.pro.annualPerMonth} per user per month billed annually, less than half the price of Loom's paid plan. Enter ${MIGRATE_PROMO_CODE} at checkout for 20% off, and the discount applies to every renewal.`,
	},
	{
		question: "How do I bulk import my whole Loom library?",
		answer:
			"Download the CSV template, add one row per video with the Loom URL, the owner's email and an optional space name, then upload it. Cap imports up to 500 videos per CSV, assigns each one to the right teammate and places it in the right space. Larger libraries run in controlled batches through the Cap CLI or MCP server, or we can run the migration for you.",
	},
	{
		question: "Can I import private or password-protected Looms?",
		answer:
			"Not while they are private. Set the video to anyone with the link on Loom, import it, and then make the Cap version private or password protected. Videos that have been deleted from Loom cannot be recovered by the importer.",
	},
	{
		question: "What happens to my Loom links after I switch?",
		answer:
			"They keep working for as long as your Loom account exists. Every imported video gets a new Cap link, so update any docs or wikis that point at Loom, then cancel Loom once you have checked the imports.",
	},
	{
		question: "How long does an import take?",
		answer:
			"A single video usually appears in your library within a few minutes. Bulk imports run in the background in batches, and the importer shows you completed and failed rows as it goes.",
	},
	{
		question: "Will I keep ownership of my recordings?",
		answer:
			"Yes. Cap is open source, and you can connect your own S3 bucket or Google Drive and a custom domain for full ownership of every recording. You can export any video as an MP4 at any time, so you are never locked in.",
	},
] as const;
