[package]
name = "cap-media-info"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg.workspace = true
thiserror.workspace = true
cpal.workspace = true

cap-ffmpeg-utils = { path = "../ffmpeg-utils" }

[lints]
workspace = true
