[package]
name = "cap-enc-mediafoundation"
version = "0.1.0"
edition = "2024"

[dependencies]
cap-media-info = { path = "../media-info" }
futures.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
	"System",
	"Graphics_Capture",
	"Graphics_DirectX_Direct3D11",
	"Foundation_Metadata",
	"Win32_Graphics_Gdi",
	"Win32_Graphics_Direct3D",
	"Win32_Graphics_Direct3D11",
	"Win32_Graphics_Dxgi_Common",
	"Win32_Graphics_Dxgi",
	"Win32_System_Com",
	"Win32_System_Com_StructuredStorage",
	"Win32_System_Ole",
	"Win32_System_Threading",
	"Win32_System_WinRT_Direct3D11",
	"Win32_System_WinRT_Graphics_Capture",
	"Win32_UI_WindowsAndMessaging",
	"Win32_Media_MediaFoundation",
	"Win32_Media_DxMediaObjects",
	"Win32_Foundation",
	"Foundation_Collections",
	"Win32_System_Variant",
	"Storage_Search",
	"Storage_Streams",
	"Win32_UI_Input",
	"Media_Core",
	"Media_MediaProperties",
	"Media_Transcoding",
	"Win32_Storage_FileSystem",
	"Win32_System_Diagnostics_Debug",
	"Win32_UI_Input_KeyboardAndMouse",
	"Security_Authorization_AppCapabilityAccess",
] }
windows-core.workspace = true
windows-numerics = "0.2.0"
scap-direct3d = { path = "../scap-direct3d" }

[dev-dependencies]
scap-targets = { path = "../scap-targets" }
clap = { version = "4.5.46", features = ["derive"] }

[lints]
workspace = true
