[package]
name = "scap-cpal"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
cpal.workspace = true
thiserror.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
