[package]
name = "cap-cpal-ffmpeg"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal.workspace = true
ffmpeg.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
