pcm_type.pulse {
	lib {
		@func concat
		strings [
			{ @func getenv vars [ APPDIR ] default "" }
			"/usr/lib/alsa-lib/libasound_module_pcm_pulse.so"
		]
	}
}

pcm.pulse {
	type pulse
	hint {
		description "PulseAudio Sound Server"
	}
}
