[package]
name = "cap-api"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
reqwest = "0.12.24"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
