/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconCapArrows: typeof import('~icons/cap/arrows.jsx')['default']
  const IconCapCamera: typeof import('~icons/cap/camera.jsx')['default']
  const IconCapChevronDown: typeof import('~icons/cap/chevron-down.jsx')['default']
  const IconCapCircle: typeof import('~icons/cap/circle.jsx')['default']
  const IconCapCircleX: typeof import('~icons/cap/circle-x.jsx')['default']
  const IconCapCrop: typeof import('~icons/cap/crop.jsx')['default']
  const IconCapEnlarge: typeof import('~icons/cap/enlarge.jsx')['default']
  const IconCapFilmCut: typeof import('~icons/cap/film-cut.jsx')['default']
  const IconCapInfo: typeof import('~icons/cap/info.jsx')['default']
  const IconCapInstant: typeof import('~icons/cap/instant.jsx')['default']
  const IconCapLogo: typeof import('~icons/cap/logo.jsx')['default']
  const IconCapLogoFull: typeof import('~icons/cap/logo-full.jsx')['default']
  const IconCapLogoFullDark: typeof import('~icons/cap/logo-full-dark.jsx')['default']
  const IconCapMicrophone: typeof import('~icons/cap/microphone.jsx')['default']
  const IconCapSettings: typeof import('~icons/cap/settings.jsx')['default']
  const IconCapSquare: typeof import('~icons/cap/square.jsx')['default']
  const IconLucideBell: typeof import('~icons/lucide/bell.jsx')['default']
  const IconLucideBug: typeof import('~icons/lucide/bug.jsx')['default']
  const IconLucideGift: typeof import('~icons/lucide/gift.jsx')['default']
  const IconLucideRectangleHorizontal: typeof import('~icons/lucide/rectangle-horizontal.jsx')['default']
  const IconLucideSquarePlay: typeof import('~icons/lucide/square-play.jsx')['default']
  const IconPhMonitorBold: typeof import('~icons/ph/monitor-bold.jsx')['default']
}
