/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconCapCamera: typeof import('~icons/cap/camera.jsx')['default']
  const IconCapChevronDown: typeof import('~icons/cap/chevron-down.jsx')['default']
  const IconCapCircleCheck: typeof import('~icons/cap/circle-check.jsx')['default']
  const IconCapCircleX: typeof import('~icons/cap/circle-x.jsx')['default']
  const IconCapCopy: typeof import('~icons/cap/copy.jsx')['default']
  const IconCapEditor: typeof import('~icons/cap/editor.jsx')['default']
  const IconCapHotkeys: typeof import('~icons/cap/hotkeys.jsx')['default']
  const IconCapLogo: typeof import('~icons/cap/logo.jsx')['default']
  const IconCapLogoFull: typeof import('~icons/cap/logo-full.jsx')['default']
  const IconCapMicrophone: typeof import('~icons/cap/microphone.jsx')['default']
  const IconCapSettings: typeof import('~icons/cap/settings.jsx')['default']
  const IconCapUpload: typeof import('~icons/cap/upload.jsx')['default']
  const IconLucideBell: typeof import('~icons/lucide/bell.jsx')['default']
  const IconLucideCamera: typeof import('~icons/lucide/camera.jsx')['default']
  const IconLucideCheck: typeof import('~icons/lucide/check.jsx')['default']
  const IconLucideDatabase: typeof import('~icons/lucide/database.jsx')['default']
  const IconLucideEdit: typeof import('~icons/lucide/edit.jsx')['default']
  const IconLucideEye: typeof import('~icons/lucide/eye.jsx')['default']
  const IconLucideFolder: typeof import('~icons/lucide/folder.jsx')['default']
  const IconLucideLayoutGrid: typeof import('~icons/lucide/layout-grid.jsx')['default']
  const IconLucideLoaderCircle: typeof import('~icons/lucide/loader-circle.jsx')['default']
  const IconLucideMessageSquarePlus: typeof import('~icons/lucide/message-square-plus.jsx')['default']
  const IconLucideSquarePlay: typeof import('~icons/lucide/square-play.jsx')['default']
}
