/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconCapAppWindowMac: typeof import('~icons/cap/app-window-mac.jsx')['default']
  const IconCapArrows: typeof import('~icons/cap/arrows.jsx')['default']
  const IconCapCamera: typeof import('~icons/cap/camera.jsx')['default']
  const IconCapChevronDown: typeof import('~icons/cap/chevron-down.jsx')['default']
  const IconCapCircleCheck: typeof import('~icons/cap/circle-check.jsx')['default']
  const IconCapCircleX: typeof import('~icons/cap/circle-x.jsx')['default']
  const IconCapCopy: typeof import('~icons/cap/copy.jsx')['default']
  const IconCapCrop: typeof import('~icons/cap/crop.jsx')['default']
  const IconCapEditor: typeof import('~icons/cap/editor.jsx')['default']
  const IconCapEnlarge: typeof import('~icons/cap/enlarge.jsx')['default']
  const IconCapLogo: typeof import('~icons/cap/logo.jsx')['default']
  const IconCapLogoFull: typeof import('~icons/cap/logo-full.jsx')['default']
  const IconCapLogoFullDark: typeof import('~icons/cap/logo-full-dark.jsx')['default']
  const IconCapLogoNobox: typeof import('~icons/cap/logo-nobox.jsx')['default']
  const IconCapMicrophone: typeof import('~icons/cap/microphone.jsx')['default']
  const IconCapMonitor: typeof import('~icons/cap/monitor.jsx')['default']
  const IconCapPadding: typeof import('~icons/cap/padding.jsx')['default']
  const IconCapScan: typeof import('~icons/cap/scan.jsx')['default']
  const IconCapSquare: typeof import('~icons/cap/square.jsx')['default']
  const IconCapUpload: typeof import('~icons/cap/upload.jsx')['default']
  const IconLucideBell: typeof import('~icons/lucide/bell.jsx')['default']
  const IconLucideEye: typeof import('~icons/lucide/eye.jsx')['default']
  const IconLucideHardDrive: typeof import('~icons/lucide/hard-drive.jsx')['default']
}
