/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const default_project_config_json: () => [number, number, number, number];
export const animated_gradient_catalog_json: () => [number, number, number, number];
export const random_animated_gradient_json: (a: number) => [number, number, number, number];
export const register_font: (a: number, b: number) => void;
export const register_asset: (a: number, b: number, c: number, d: number) => void;
export const register_decoded_asset: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const has_asset: (a: number, b: number) => number;
export const remove_asset: (a: number, b: number) => void;
export const web_input_recording: (a: number, b: number) => [number, number, number, number];
export const __wbg_browsertimeline_free: (a: number, b: number) => void;
export const browsertimeline_new: (a: number, b: number) => [number, number, number];
export const browsertimeline_map_frame: (a: number, b: number) => [number, number];
export const __wbg_browserrecordingtimes_free: (a: number, b: number) => void;
export const browserrecordingtimes_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const browserrecordingtimes_source_times: (a: number, b: number, c: number) => [number, number];
export const browserrecordingtimes_audio_times: (a: number, b: number, c: number) => [number, number];
export const __wbg_browservisualconfig_free: (a: number, b: number) => void;
export const browservisualconfig_new: (a: number, b: number) => [number, number, number];
export const browservisualconfig_output_dimensions: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browservisualconfig_aspect_locked: (a: number) => number;
export const __wbg_browserstudiorenderer_free: (a: number, b: number) => void;
export const browserstudiorenderer_create: (a: any, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const browserstudiorenderer_backend: (a: number) => [number, number];
export const browserstudiorenderer_max_texture_dimension: (a: number) => number;
export const browserstudiorenderer_set_project: (a: number, b: number, c: number) => [number, number];
export const browserstudiorenderer_set_cursor: (a: number, b: number, c: number, d: number) => [number, number];
export const browserstudiorenderer_output_size: (a: number, b: number, c: number) => [number, number];
export const browserstudiorenderer_render: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: any, k: number) => [number, number, number, number];
export const browserstudiorenderer_render_transition: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: any, k: number, l: number, m: number, n: any, o: number, p: any, q: number, r: number, s: number) => [number, number, number, number];
export const browserstudiorenderer_redraw_last: (a: number) => number;
export const browserstudiorenderer_snapshot_rgba: (a: number) => any;
export const browserstudiorenderer_last_layout: (a: number) => [number, number];
export const webgl2_available: (a: any) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure1244_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h206b19c123560cb9: (a: number, b: number) => void;
export const closure1628_externref_shim: (a: number, b: number, c: any) => void;
export const closure2700_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
