/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const default_project_config_json: () => [number, number, number, number];
export const animated_gradient_catalog_json: () => [number, number, number, number];
export const random_animated_gradient_json: (a: number) => [number, number, number, number];
export const __wbg_browsertimeline_free: (a: number, b: number) => void;
export const browsertimeline_new: (a: number, b: number) => [number, number, number];
export const browsertimeline_map_frame: (a: number, b: number) => [number, number];
export const __wbg_browserrecordingtimes_free: (a: number, b: number) => void;
export const browserrecordingtimes_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const browserrecordingtimes_source_times: (a: number, b: number, c: number) => [number, number];
export const browserrecordingtimes_audio_times: (a: number, b: number, c: number) => [number, number];
export const __wbg_browsergpurenderer_free: (a: number, b: number) => void;
export const browsergpurenderer_create: (a: any) => any;
export const browsergpurenderer_createWebGl: (a: any) => any;
export const browsergpurenderer_backend: (a: number) => [number, number];
export const browsergpurenderer_set_background: (a: number, b: number, c: number) => [number, number];
export const browsergpurenderer_set_frame_time: (a: number, b: number, c: number) => [number, number];
export const browsergpurenderer_resize: (a: number, b: number, c: number) => [number, number];
export const browsergpurenderer_render: (a: number, b: any, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const browsergpurenderer_render_transition: (a: number, b: any, c: number, d: number, e: number, f: number, g: number, h: any, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => [number, number];
export const browsergpurenderer_redraw_last: (a: number) => [number, number, number];
export const browsergpurenderer_snapshot_rgba: (a: number) => any;
export const default_layer_uniforms: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const __wbg_browservisualconfig_free: (a: number, b: number) => void;
export const browservisualconfig_new: (a: number, b: number) => [number, number, number];
export const browservisualconfig_output_dimensions: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browservisualconfig_layer_uniforms: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const closure380_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h147cdb123ff2ae0f: (a: number, b: number) => void;
export const closure1450_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
