// Generated by Wrangler by running `wrangler types`

interface Env {
	release_discord_interactions: KVNamespace;
	DISCORD_BOT_TOKEN: string;
	GITHUB_APP_ID: string;
	GITHUB_APP_PRIVATE_KEY: string;
}
