/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconLucideCopy: typeof import('~icons/lucide/copy.jsx')['default']
  const IconLucideEye: typeof import('~icons/lucide/eye.jsx')['default']
  const IconLucidePencil: typeof import('~icons/lucide/pencil.jsx')['default']
  const IconLucidePenicl: typeof import('~icons/lucide/penicl.jsx')['default']
  const IconLucideShare: typeof import('~icons/lucide/share.jsx')['default']
}
