import Header from "./components/Header";
import OtherStats, { type OtherStatsData } from "./components/OtherStats";
import StatsChart from "./components/StatsChart";

export default function AnalyticsPage() {
	return (
		<div className="space-y-8">
			<Header />
			<StatsChart
				counts={{
					caps: "524",
					views: "2,768",
					chats: "100",
					reactions: "170",
				}}
			/>
			<OtherStats data={mockData} />
		</div>
	);
}

const mockData: OtherStatsData = {
	countries: [
		{
			countryCode: "US",
			name: "United States",
			views: "8,452",
			comments: "100",
			reactions: "100",
			percentage: "34.2%",
		},
		{
			countryCode: "GB",
			name: "United Kingdom",
			views: "3,891",
			comments: "100",
			reactions: "100",
			percentage: "15.7%",
		},
		{
			countryCode: "CA",
			name: "Canada",
			views: "2,764",
			comments: "100",
			reactions: "100",
			percentage: "11.2%",
		},
		{
			countryCode: "DE",
			name: "Germany",
			views: "2,143",
			comments: "100",
			reactions: "100",
			percentage: "8.7%",
		},
		{
			countryCode: "FR",
			name: "France",
			views: "1,876",
			comments: "100",
			reactions: "100",
			percentage: "7.6%",
		},
		{
			countryCode: "AU",
			name: "Australia",
			views: "1,542",
			comments: "100",
			reactions: "100",
			percentage: "6.2%",
		},
		{
			countryCode: "JP",
			name: "Japan",
			views: "1,298",
			comments: "100",
			reactions: "100",
			percentage: "5.2%",
		},
		{
			countryCode: "BR",
			name: "Brazil",
			views: "987",
			comments: "100",
			reactions: "100",
			percentage: "4.0%",
		},
	],
	cities: [
		{
			countryCode: "US",
			name: "New York",
			views: "3,421",
			comments: "100",
			reactions: "100",
			percentage: "18.7%",
		},
		{
			countryCode: "US",
			name: "Los Angeles",
			views: "2,876",
			comments: "100",
			reactions: "100",
			percentage: "15.7%",
		},
		{
			countryCode: "GB",
			name: "London",
			views: "2,145",
			comments: "100",
			reactions: "100",
			percentage: "11.7%",
		},
		{
			countryCode: "CA",
			name: "Toronto",
			views: "1,892",
			comments: "100",
			reactions: "100",
			percentage: "10.3%",
		},
		{
			countryCode: "US",
			name: "San Francisco",
			views: "1,654",
			comments: "100",
			reactions: "100",
			percentage: "9.0%",
		},
		{
			countryCode: "US",
			name: "Chicago",
			views: "1,432",
			comments: "100",
			reactions: "100",
			percentage: "7.8%",
		},
		{
			countryCode: "DE",
			name: "Berlin",
			views: "1,198",
			comments: "100",
			reactions: "100",
			percentage: "6.5%",
		},
		{
			countryCode: "US",
			name: "Seattle",
			views: "987",
			comments: "100",
			reactions: "100",
			percentage: "5.4%",
		},
		{
			countryCode: "AU",
			name: "Sydney",
			views: "876",
			comments: "100",
			reactions: "100",
			percentage: "4.8%",
		},
		{
			countryCode: "FR",
			name: "Paris",
			views: "743",
			comments: "100",
			reactions: "100",
			percentage: "4.1%",
		},
		{
			countryCode: "US",
			name: "Boston",
			views: "621",
			comments: "100",
			reactions: "100",
			percentage: "3.4%",
		},
	],
	browsers: [
		{
			browser: "google-chrome",
			name: "Chrome",
			views: "12,456",
			comments: "100",
			reactions: "100",
			percentage: "42.3%",
		},
		{
			browser: "safari",
			name: "Safari",
			views: "6,234",
			comments: "100",
			reactions: "100",
			percentage: "21.2%",
		},
		{
			browser: "firefox",
			name: "Firefox",
			views: "4,187",
			comments: "100",
			reactions: "100",
			percentage: "14.2%",
		},
		{
			browser: "explorer",
			name: "Edge",
			views: "3,542",
			comments: "100",
			reactions: "100",
			percentage: "12.0%",
		},
		{
			browser: "brave",
			name: "Brave",
			views: "1,876",
			comments: "100",
			reactions: "100",
			percentage: "6.4%",
		},
		{
			browser: "opera",
			name: "Opera",
			views: "654",
			comments: "100",
			reactions: "100",
			percentage: "2.2%",
		},
		{
			browser: "vivaldi",
			name: "Vivaldi",
			views: "298",
			comments: "100",
			reactions: "100",
			percentage: "1.0%",
		},
		{
			browser: "yandex",
			name: "Yandex",
			views: "143",
			comments: "100",
			reactions: "100",
			percentage: "0.5%",
		},
		{
			browser: "duckduckgo",
			name: "DuckDuckGo",
			views: "67",
			comments: "100",
			reactions: "100",
			percentage: "0.2%",
		},
	],
	operatingSystems: [
		{
			os: "windows",
			name: "Windows",
			views: "9,876",
			comments: "100",
			reactions: "100",
			percentage: "38.7%",
		},
		{
			os: "ios",
			name: "macOS",
			views: "7,432",
			comments: "100",
			reactions: "100",
			percentage: "29.1%",
		},
		{
			os: "linux",
			name: "Linux",
			views: "3,654",
			comments: "100",
			reactions: "100",
			percentage: "14.3%",
		},
		{
			os: "ubuntu",
			name: "Ubuntu",
			views: "2,187",
			comments: "100",
			reactions: "100",
			percentage: "8.6%",
		},
		{
			os: "fedora",
			name: "Fedora",
			views: "1,243",
			comments: "100",
			reactions: "100",
			percentage: "4.9%",
		},
	],
	deviceTypes: [
		{
			device: "desktop",
			name: "Desktop",
			views: "2,456",
			comments: "100",
			reactions: "100",
			percentage: "45.6%",
		},
		{
			device: "tablet",
			name: "Tablet",
			views: "1,234",
			comments: "100",
			reactions: "100",
			percentage: "23.4%",
		},
		{
			device: "mobile",
			name: "Mobile",
			views: "1,789",
			comments: "100",
			reactions: "100",
			percentage: "30.9%",
		},
	],
	topCaps: [
		{
			name: "Product Demo - Q4 2024",
			views: "5,842",
			comments: "100",
			reactions: "100",
			percentage: "28.3%",
		},
		{
			name: "Tutorial: Getting Started",
			views: "4,156",
			comments: "100",
			reactions: "100",
			percentage: "20.1%",
		},
		{
			name: "Team Meeting Highlights",
			views: "3,421",
			comments: "100",
			reactions: "100",
			percentage: "16.6%",
		},
		{
			name: "Bug Fix Walkthrough",
			views: "2,789",
			comments: "100",
			reactions: "100",
			percentage: "13.5%",
		},
		{
			name: "Feature Announcement",
			views: "1,923",
			comments: "100",
			reactions: "100",
			percentage: "9.3%",
		},
		{
			name: "Customer Feedback Review",
			views: "1,245",
			comments: "100",
			reactions: "100",
			percentage: "6.0%",
		},
		{
			name: "Sprint Retrospective",
			views: "876",
			comments: "100",
			reactions: "100",
			percentage: "4.2%",
		},
		{
			name: "Design System Update",
			views: "543",
			comments: "100",
			reactions: "100",
			percentage: "2.6%",
		},
		{
			name: "API Documentation Demo",
			views: "289",
			comments: "100",
			reactions: "100",
			percentage: "1.4%",
		},
	],
};
